name: Firebase Deploy

on:
  push:
    branches:
      - main  # Replace with your branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run build script if you have one
      - name: Build project
        run: npm run build:web
      
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v4.3.0
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
